FROM python:3.14-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.8.22 /uv /uvx /bin/

COPY pyproject.toml .
COPY uv.lock .
COPY src/ src/

RUN uv sync --locked --no-dev

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "gamingclock.main:app", "--host", "0.0.0.0", "--port", "8000"]
